# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import med_schedule_pb2 as med__schedule__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in med_schedule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MedicationScheduleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSchedule = channel.unary_unary(
                '/med_schedule.MedicationScheduleService/CreateSchedule',
                request_serializer=med__schedule__pb2.ScheduleCreateRequest.SerializeToString,
                response_deserializer=med__schedule__pb2.ScheduleResponse.FromString,
                _registered_method=True)
        self.GetUserSchedules = channel.unary_unary(
                '/med_schedule.MedicationScheduleService/GetUserSchedules',
                request_serializer=med__schedule__pb2.UserSchedulesRequest.SerializeToString,
                response_deserializer=med__schedule__pb2.UserSchedulesResponse.FromString,
                _registered_method=True)
        self.GetScheduleDetail = channel.unary_unary(
                '/med_schedule.MedicationScheduleService/GetScheduleDetail',
                request_serializer=med__schedule__pb2.ScheduleDetailRequest.SerializeToString,
                response_deserializer=med__schedule__pb2.ScheduleDetailResponse.FromString,
                _registered_method=True)
        self.GetNextTakings = channel.unary_unary(
                '/med_schedule.MedicationScheduleService/GetNextTakings',
                request_serializer=med__schedule__pb2.NextTakingsRequest.SerializeToString,
                response_deserializer=med__schedule__pb2.NextTakingsResponse.FromString,
                _registered_method=True)


class MedicationScheduleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSchedule(self, request, context):
        """Создание нового расписания
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserSchedules(self, request, context):
        """Получение списка расписаний пользователя
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleDetail(self, request, context):
        """Получение деталей конкретного расписания
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextTakings(self, request, context):
        """Получение ближайших приёмов лекарств
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MedicationScheduleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=med__schedule__pb2.ScheduleCreateRequest.FromString,
                    response_serializer=med__schedule__pb2.ScheduleResponse.SerializeToString,
            ),
            'GetUserSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSchedules,
                    request_deserializer=med__schedule__pb2.UserSchedulesRequest.FromString,
                    response_serializer=med__schedule__pb2.UserSchedulesResponse.SerializeToString,
            ),
            'GetScheduleDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleDetail,
                    request_deserializer=med__schedule__pb2.ScheduleDetailRequest.FromString,
                    response_serializer=med__schedule__pb2.ScheduleDetailResponse.SerializeToString,
            ),
            'GetNextTakings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextTakings,
                    request_deserializer=med__schedule__pb2.NextTakingsRequest.FromString,
                    response_serializer=med__schedule__pb2.NextTakingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'med_schedule.MedicationScheduleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('med_schedule.MedicationScheduleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MedicationScheduleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/med_schedule.MedicationScheduleService/CreateSchedule',
            med__schedule__pb2.ScheduleCreateRequest.SerializeToString,
            med__schedule__pb2.ScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/med_schedule.MedicationScheduleService/GetUserSchedules',
            med__schedule__pb2.UserSchedulesRequest.SerializeToString,
            med__schedule__pb2.UserSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduleDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/med_schedule.MedicationScheduleService/GetScheduleDetail',
            med__schedule__pb2.ScheduleDetailRequest.SerializeToString,
            med__schedule__pb2.ScheduleDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextTakings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/med_schedule.MedicationScheduleService/GetNextTakings',
            med__schedule__pb2.NextTakingsRequest.SerializeToString,
            med__schedule__pb2.NextTakingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
