// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table schedules {
  schedule_id bigint
  user_id bigint
  name varchar(255)
  frequency varchar(255)
  duration varchar(255)
  start_time time
  end_time time

  indexes {
    (schedule_id) [type: primary]
  }
}
